# mluckydwyer/hw-ci Docker Container
FROM mluckydwyer/hw-ci:slim as slim

LABEL \
    org.opencontainers.image.title="Hardware Verification CI Docker container" \
    org.opencontainers.image.description="Modelsim, Verilator, GHDL, VUnit, CocoTB, and Pytest for HW Development (+VNC)." \
    org.opencontainers.image.authors="Matthew Dwyer <dwyer@iastate.edu>" \
    org.opencontainers.image.source="https://github.com/Mluckydwyer/hw-ci"

ENV container docker


# Patch CocoTB-test simulation.py with custom implementation for Modelsim complilation
# RUN rm /opt/Python-3.6.14/lib/python3.6/site-packages/cocotb_test/simulator.py
# COPY resources/simulator.py /opt/Python-3.6.14/lib/python3.6/site-packages/cocotb_test/simulator.py
# EXPOSE 5678

# Install VUnit
FROM slim as vunit
RUN pip3 install vunit_hdl


# Install Modelsim
FROM vunit as modelsim
RUN yum install -y libiodbc unixODBC ncurses ncurses-libs \
    zeromq-devel libXext alsa-lib libXtst libXft libxml2 libedit libX11 libXi \
    glibc glibc.i686 glibc-devel.i386 libgcc.i686 libstdc++-devel.i686 libstdc++ \
    libstdc++.i686 libXext libXext.i686 libXft libXft.i686 libXrender libXtst
WORKDIR /tmp
RUN curl -sS -O https://download.altera.com/akdlm/software/acdsinst/20.1std.1/720/ib_installers/ModelSimSetup-20.1.1.720-linux.run \
    && chmod +x ModelSimSetup-20.1.1.720-linux.run \
    && ./ModelSimSetup-20.1.1.720-linux.run --mode unattended --installdir /opt/intelFPGA/20.1 --accept_eula 1 --modelsim_edition modelsim_ase \
    && rm ModelSimSetup-20.1.1.720-linux.run
ENV PATH="/opt/intelFPGA/20.1/modelsim_ase/bin:${PATH}"


# Yosys synthesis
# FROM slim as yosys
# RUN mkdir /tmp/yosys \
#     && curl -sSL https://github.com/YosysHQ/yosys/archive/refs/tags/yosys-0.14.tar.gz | tar -xz -C /tmp/yosys --strip-components=1 \
#     && cd /tmp/yosys \
#     && make \
#     && make install \
#     && rm -rf /tmp/

# Add VHDL support


# Install Symbiflow toolchain
# FROM modelsim as symbiflow
# ENV SYMBIFLOW_INSTALL_DIR=/opt/symbiflow
# ENV PATH=$SYMBIFLOW_INSTALL_DIR/xc7/:$PATH
# WORKDIR /workspaces/
# RUN yum -y install git which xz \
#     && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/Miniconda3-latest-Linux-x86_64.sh \
#     && sh /tmp/Miniconda3-latest-Linux-x86_64.sh -u -b -p ${SYMBIFLOW_INSTALL_DIR}/conda \
#     && git clone https://github.com/SymbiFlow/symbiflow-examples \
#     && cd symbiflow-examples \
#     && source "${SYMBIFLOW_INSTALL_DIR}/conda/etc/profile.d/conda.sh" \
#     && conda env create -f xc7/environment.yml \
#     && conda env create -f eos-s3/environment.yml \
#     && mkdir -p $SYMBIFLOW_INSTALL_DIR/{xc7,eos-s3}/install \
#     && curl -sSL https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/535/20220128-000432/symbiflow-arch-defs-install-5fa5e715.tar.xz | tar -xJC ${SYMBIFLOW_INSTALL_DIR}/xc7/install \
#     && curl -sSL https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/535/20220128-000432/symbiflow-arch-defs-xc7a50t_test-5fa5e715.tar.xz | tar -xJC ${SYMBIFLOW_INSTALL_DIR}/xc7/install \
#     && curl -sSL https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/535/20220128-000432/symbiflow-arch-defs-xc7a100t_test-5fa5e715.tar.xz | tar -xJC ${SYMBIFLOW_INSTALL_DIR}/xc7/install \
#     && curl -sSL https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/535/20220128-000432/symbiflow-arch-defs-xc7a200t_test-5fa5e715.tar.xz | tar -xJC ${SYMBIFLOW_INSTALL_DIR}/xc7/install \
#     && curl -sSL https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/535/20220128-000432/symbiflow-arch-defs-xc7z010_test-5fa5e715.tar.xz | tar -xJC ${SYMBIFLOW_INSTALL_DIR}/xc7/install \
#     && curl -sSL https://storage.googleapis.com/symbiflow-arch-defs-install/quicklogic-arch-defs-63c3d8f9.tar.gz | tar -xzC ${SYMBIFLOW_INSTALL_DIR}/eos-s3/install \
#     && rm /tmp/Miniconda3-latest-Linux-x86_64.sh

FROM modelsim as final
WORKDIR /workspaces/

