name: Build Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-slim:
    name: "Build slim container"
    runs-on: ubuntu-latest
    steps:
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile-Slim
        push: true
        tags: mluckydwyer/hw-ci:slim,mluckydwyer/hw-ci:latest
        cache-from: type=registry,ref=mluckydwyer/hw-ci:buildcache
        cache-to: type=registry,ref=mluckydwyer/hw-ci:buildcache,mode=max
  build-full:
    name: "Build full container"
    runs-on: ubuntu-latest
    needs: build-slim
    steps:
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile-Full
        push: true
        tags: mluckydwyer/hw-ci:full
        cache-from: type=registry,ref=mluckydwyer/hw-ci:buildcache
        cache-to: type=registry,ref=mluckydwyer/hw-ci:buildcache,mode=max
